services:
  return-web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NODE_ENV: production
    volumes:
      - ./src/data:/app/src/data
